

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"
  jobs:
    post_install:
      # Install dependencies defined in your ``package.json``
      - npm ci
      # Install any other extra dependencies to build the docs
      - npm install -g jsdoc

mkdocs:
  configuration: docs/mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  install:
  - requirements: conf/requirements.txt

search:
   ignore:
     - resources/*
     - .github/*
     - .gitignore
     - .npmrc
     - .npmignore

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#    install:
#    - requirements: docs/requirements.txt
