module.exports={
  jsonExt:require("./json-gadgets.js"),
  caseChange:require("./case-gadgets.js"),
  randomString:require('./random-string.js'),
  primeNum:require('./find-prime-number.js').primeNumber,
  antiPrimeNum:require('./find-prime-number.js').powerOfTwo,
  musicaledCiphers:require('./music-easteregged-cryptography.js'),
  Fibonacci:require('./fibonacci.js')
}
